### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by Nyoko74** [cyj407/DiSS#2]
Hi, I try to run `train.py` with my dataset. but get an exception: StopIteration
In  File `"/DiSS-master/guided_diffusion/guided_diffusion/train_util.py"`, line 158, in run_loop:
`batch, cond = next(self.data)`
And I'm curious what `batch` and `cond` mean？

**Comment by Nyoko74** [comment]
I make it work by delete `return dataset` in `load_data_sketchstroke()`.
And modify `batch, cond = next(self.data)` to `image, sketch, stroke, cond = next(self.data)` in `run_loop()`, and corresponding modification made in `run_step()` and `forward_backward()`.

**Comment by SHINICHENG** [comment]
Thank you for your interest in our paper and for bringing up the issues. We have updated the codes and fixed the bugs, Thanks again!
