### ISSUE TITLE
About the Stroke Generation

### ISSUE THREAD

**Issue by SongYxing** [cyj407/DiSS#3]
Thanks for your wonderful work.
In your paper,the stroke of AFHQ was generated by Stylized Neural Painting.Stylized Neural Painting has four types(Photo to oil painting、Photo to marker-pen painting、Style transfer、Generate 8-bit graphic artworks) to choose,I want to know which one you run.

**Comment by SHINICHENG** [comment]
Thank you for your interest. We use "Photo to oil painting" mode in Stylized Neural Painting to generate our stroke data.
