### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by faixan-khan** [cyj407/DiSS#7]
Thank you for the wonderful work. 
I was curious about how long did it take to train the model?

**Comment by kako523** [comment]
I also have this question, I am now using 1000 pictures for training, has been training for 36h, do not know how long to train. Can you let me know if you already know the training time? Thank you very much!

**Comment by cyj407** [comment]
Hi, with 5000 training images, we trained the model for around 3~4 days by using one 3090turbo GPU.
